name: RSS Monitor
on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-rss-monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set permission to write to repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Specify exact version for consistency
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
      
      - name: Run RSS script
        run: python rss_monitor.py
        
      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -f data/rss_feeds.db index.html data/rss_monitor.log  # Force add in case files are gitignored
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "Update RSS results - $timestamp" || echo "No changes to commit"
          git push || (git pull --rebase && git push)
